# Generated by Django 4.2.27 on 2026-03-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0005_teachersalary_studentfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLessonTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('target_lessons', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.teacher')),
            ],
            options={
                'unique_together': {('teacher', 'date')},
            },
        ),
    ]
