# Generated by Django 4.2.27 on 2026-03-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_dailylessontarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
