# Generated by Django 4.2.27 on 2026-03-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_salaryrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='venue',
            field=models.CharField(default='Main Hall', max_length=100),
        ),
    ]
