# Generated by Django 4.2.27 on 2026-04-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0014_systemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
